[package]
name = "reerio"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version="4.5.48", features=["derive"] }
ego-tree = "0.10.0"
reqwest = { version="0.12.23", features = ["json", "blocking", "gzip"] }
scraper = "0.24.0"
tokio = { version = "1.47.1", features = ["full"] }
